// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfjkeczihhgrvfqrbudn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmamtlY3ppaGhncnZmcXJidWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzc4MDUsImV4cCI6MjA2Mjg1MzgwNX0.IWjaC8OEpQjdxAJ8-xpXd2qGYLGgxtB2tNrDVGf6ZP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);